### PR TITLE
Added proxy support

### PR DESCRIPTION
**Pull request by kubac65**
Change checks whether `http.proxy` option is provided and applies, that setting for the http requests.

### CODE REVIEW

**Comment by mre** [comment]
Thanks @kubac65.

Is the `http-proxy-agent` missing in the `package.json`?
I had to do an `npm install http-proxy-agent --save` to get it running.

Also, we might want to add some information about this to the `README.md`.

**Comment by kubac65** [comment]
I must have overlooked the `package.json` when I was committing the changes. It's fixed now, and docs are updated as well.

**Comment by mre** [comment]
Thanks! Just saw that the new property might be missing in the `package.json`. It should be here, I guess: https://github.com/mre/vscode-snippet/blob/06cefc5c3f14ad1f2584521acbf9f69947519998/package.json#L71

**Comment by kubac65** [comment]
`http.proxy` is not a property specific to this extension. It's a setting which is available in vscode configuration. [see reference](https://code.visualstudio.com/docs/setup/network#_legacy-proxy-server-support)

Instead of adding a redundant property to the extension. I'm reusing the one already defined by the application. Therefore I don't think that it needs to be added to the `package.json` file.

**Comment by mre** [comment]
Gotcha. Thanks for the clarification. :shipit: 🎉

**Pull request merged**
