### PR TITLE
Fix а failing test

### PR DESCRIPTION
**Pull request by VladBrok**
image

### CODE REVIEW

**Comment by mre** [comment]
Nice. Node 16 is still failing, but I don't know why.

**Comment by VladBrok** [comment]
This is because an action triggered by "pull_request_target" [runs in the pull request's target branch, and not the pull request's branch itself.](https://stackoverflow.com/questions/74957218/what-is-the-difference-between-pull-request-and-pull-request-target-event-in-git)
I changed it to "pull_request".

**Comment by VladBrok** [comment]
It should work fine after merge

**Comment by mre** [comment]
Merge. Fingers crossed. 🤞 Thanks for the investigation!

**Pull request merged**
