### PR TITLE
Implement live suggestions

### LINKED ISSUE #5: Provide live suggestions for user input
We should have an option for suggesting snippets while a user is typing a query.
Gitlens provides the same functionality.

See https://github.com/eamodio/vscode-gitlens

### PR DESCRIPTION
**Pull request by GianOrtiz**
Implemented a way to save past queries in cache and changed InputBox for QuickPick as a way to provide past queries as suggestions.

Probably will work as fixes #5 for now.

### CODE REVIEW

**Comment by mre** [comment]
Just tested this, and I got a weird error message on line 42:

```
[ts] Property 'createQuickPick' does not exist on type 'typeof window'.
```

No idea why. I'm using the latest VSCode (1.28.1), and the documentation says it exists:
https://code.visualstudio.com/docs/extensionAPI/vscode-api
Any ideas?

**Comment by GianOrtiz** [comment]
Github crashed and I made some mistakes, commented the same comment many times and closed the pull request thinking that the error was with me. But while github was down, I found a workaround (e392285). It works well here.

**Comment by mre** [comment]
Thanks for working on this. Just tried it on my machine and while it does run now, I get no suggestions. I was expecting that they would show up when the search window gets opened.
Is there any trick to show the suggestions?

**Comment by GianOrtiz** [comment]
If I use `Snippet: Find` without searching anything after cache is implemented what I get is no results:

semresultado

But if I use `Snippet: Find`after searching something with cache what I get is:

comresultados

This is the result that I get, i don't understand either why this is happening with you.

**Comment by mre** [comment]
When I try to run this in the debugger, I get the following error:

```javascript
{
	"resource": "/Users/mendler/Code/private/vscode-snippet/src/extension.ts",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type '{ label: any; }' is not assignable to type 'QuickPickItem'.\n  Property 'description' is missing in type '{ label: any; }'.",
	"source": "ts",
	"startLineNumber": 41,
	"startColumn": 9,
	"endLineNumber": 41,
	"endColumn": 22
}
```

If I change 

```javascript
tempQuickItem = { label: suggestions[key] }
```

to 

```javascript
tempQuickItem = { label: suggestions[key], description: "" }
```

it at least starts. But then I get the following error when running snippet:

```
Running the contributed command:'snippet.find' failed.
```

Don't know what to do with that. 😅

**Comment by GianOrtiz** [comment]
I probably figured out why we are getting different results from this pull request and it is totally my fault . 

The errors in  https://github.com/mre/vscode-snippet/pull/13#issuecomment-431907070 and https://github.com/mre/vscode-snippet/pull/13#issuecomment-434015144 is due to the cache never be initiated.

While developing in my local repository I've reseted the cache many times to the basic class Node and never runned with files that are not plaintext, which I tought was not going to be a problem.

I could replicate your errors because I installed a new linux distro and tried the changes there, and get the same errors. When I have some time, probably this weekend, I will investigate if the errors were caused by this.

Also, adding these lines:

```typescript
    let tree = cache.state.get(`snippet_${language}`)
    if(!tree) {
        let newTree = new Node(`snippet_${language}`)
        cache.state.update(`snippet_${language}`, newTree)
        tree = cache.state.get(`snippet_${language}`)
    }
```

after the line 33 https://github.com/GianOrtiz/vscode-snippet/blob/1b457033c04b4d82cdc4b143256f6c97e3576ba4/src/extension.ts#L33 solved the errors for me. But, I will investigate better in this weekend.

**Comment by GianOrtiz** [comment]
While reading again the code from this pull request I cannot see why I am using a tree data structure, if I am transforming all of its content in an array. I could just create a simple Object and save the content of queries in there. It won't need to use all those functions and problably will be faster. So I will close this pull request and create a new one when I come up with the proposed improvements.

**Pull request closed without merging**
