### PR TITLE
Add defaultLanguage configuration option

### PR DESCRIPTION
**Pull request by GianOrtiz**
As discussed in #19 this PR creates a new configuration option to allow users set a default language to use whenever the find command is used and there is no open editor window.

### CODE REVIEW

**Comment by mre** [comment]
Looks good to me. I'll test it tonight.

**Comment by mre** [comment]
Would also like to send you the VSCode Marketplace credentials so you can release the new version yourself after the merge. Would that be okay? If so, shall I use your e-mail address from the git log?

**Comment by mre** [comment]
Looks good. Tested locally and it works but I couldn't get it to print the error message "There is no open editor window", even though I started a new vscode instance without any open editor... 🤔

**Comment by GianOrtiz** [comment]
> Would also like to send you the VSCode Marketplace credentials so you can release the new version yourself after the merge. Would that be okay? If so, shall I use your e-mail address from the git log?

Sure, you can use the email from the git log.

> Looks good. Tested locally and it works but I couldn't get it to print the error message "There is no open editor window", even though I started a new vscode instance without any open editor... thinking

I did get the error message when there is no open editor. I've changed the code(https://github.com/GianOrtiz/vscode-snippet/blob/default-language-config/src/extension.ts#L56) to send the error message when the `defaultLanguage` config option is just whitespaces and to send the error message when the `findInplace` command is executed. When you have some time please try to test it again, I couldn't reproduce the error locally, even tried to package the extension and install it manually and I got the error message.

**Comment by mre** [comment]
Alright I had the log open so it detected "Log" as the current language. -.-
Works beautifully!
Please merge and release to your liking. 😊 
I sent you a release token via mail. 🎉

**Pull request merged**
