### PR TITLE
CI

### PR DESCRIPTION
**Pull request by VladBrok**

### CODE REVIEW

**Comment by mre** [comment]
Thanks a lot for this. Looks solid, even though I haven't tested it. I think we can merge this and see if it works unless you want to make any additional changes. What do you think?

**Comment by VladBrok** [comment]
Yeah, let's merge this

**Comment by mre** [comment]
Getting an error: https://github.com/mre/vscode-snippet/actions/runs/3824512962/jobs/6506730836
Looks like we need to install `tsc` for the release.

**Comment by VladBrok** [comment]
It actually occurs because PUBLISHER_TOKEN is not set (https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token). It should be added to repository secrets (repository settings -> secrets -> actions -> new repository secret)

**Comment by VladBrok** [comment]
If release runs with token, it does not use tsc at all

**Comment by mre** [comment]
Oh, sorry. My bad. Thanks for the detailed explanation. I've added the token now and get a different error message:

```
Publishing 'vscode-snippet.snippet v0.8.1'...
Error: vscode-snippet.snippet v0.8.1 already exists.
```

That's fine, because we haven't bumped the version number. 😉 
I'll go ahead and set it to 0.9.0 and we'll see if it works.

Maybe we should only create a release when we create a new tag.

**Comment by VladBrok** [comment]
Yeah, I forgot about versions. Indeed, it would be better for the release to be created when the new tag is created)

**Comment by mre** [comment]
0.9.0 was already released and I forgot to bump the version number in the `package.json`. 🙄 
I published 0.9.1 now and the release pipeline passed. I can see the new release on the [Marketplace](https://marketplace.visualstudio.com/items?itemName=vscode-snippet.Snippet). 🙏 
@VladBrok if you like you can make the condition to check for a tag. It's not urgent, though.

**Pull request merged**
