### PR TITLE
Update Github Actions workflow (ci.yml) (reopened)

### PR DESCRIPTION
**Pull request by Maks1mS**
Reopened #205.

### CODE REVIEW

**Comment by Maks1mS** [comment]
sad-face

**Comment by VladBrok** [comment]
Looks like the workflow runs in the forked repository https://github.com/Maks1mS/vscode-snippet/actions/runs/4098339296 but doesn't run here :thinking:

**Comment by Maks1mS** [comment]
I will disable Actions in fork to check.

**Comment by mre** [comment]
Strange. Usually we have to approve workflows for first-time contributors as per https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks. I don't see such a button here. 🤔

**Comment by VladBrok** [comment]
I approved workflow, it executed and failed firstly, but stopped executing on subsequent commits
image

**Comment by mre** [comment]
That's weird.

**Comment by Maks1mS** [comment]
Perhaps we should merge it into a separate branch, for example `mre:update-ci`, and then try to create a pull request from `mre:update-ci` into `mre:master` ?

**Comment by mre** [comment]
Yes, that should always work. We can do that. 👍 I just don't understand why CI doesn't run on your fork at the moment.
My guess is that previously we used `pull_request` as a trigger (which runs on the source branch) and only later in this pull request changed it to `pull_request_target`, which runs on the base branch:

> Note: Workflows triggered by pull_request_target events are run in the context of the base branch. Since the base branch is considered trusted, workflows triggered by these events will always run, regardless of approval settings.

([Source](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks))

Maybe that's what trips it up.
This should be resolved with future pull requests, though, once we merge this PR in.
I might be completely wrong of course.

Let me create a PR for `mre:update-ci`.

**Pull request closed without merging**
