### PR TITLE
Add "Snippets" view

### PR DESCRIPTION
**Pull request by VladBrok**
#191

### CODE REVIEW

**Comment by mre** [comment]
Looks good to me. Is this ready for review? Then I'd give it a spin on my local machine.

**Comment by VladBrok** [comment]
Yeah, it's ready

**Comment by VladBrok** [comment]
@mre thanks for the great suggestions, I implemented them)

**Comment by mre** [comment]
Very nice. I'm at fosdem right now. Will check tomorrow

**Comment by mre** [comment]
Looks great! I've tested it thoroughly and found no issues. Also, thanks for adding many sanity checks. I was pleasantly surprised that you handle cases like no open files when trying to save a snippet for example.

Merging. 🎉

**Comment by mre** [comment]
Feel free to cut a new release. 😃

**Comment by mre** [comment]
I'm thinking we could make this a pre-1.0 release. If users don't report any bugs we can do a 1.0 next.

**Comment by VladBrok** [comment]
> I'm thinking we could make this a pre-1.0 release. If users don't report any bugs we can do a 1.0 next.

sure

**Pull request merged**
