### PR TITLE
Improvement: code refactory

### PR DESCRIPTION
**Pull request by yurireeis**
**About Pull Request**

What We Have done?

As requested by vscode-snippet project owner ( @mre ), this commit aims to eliminate duplicated code and set best practices.

I've used three linters to achieve this goal: TSLinter,  JacksonLinter and Node Security.

Related: https://github.com/mre/vscode-snippet/issues/22

What We have to test?

I need some clarification to test locally (original project Doesn't have an explanation on how We could up the project and test)

### CODE REVIEW

**Comment by mre** [comment]
Hey @yurireeis,
just wanted to say thanks for your PR. I'll look into it as soon as #27 is through. It might require some rebasing, but overall we should get some great improvements out of your cleanup.
Thanks.

**Comment by yurireeis** [comment]
> Hey @yurireeis,
> just wanted to say thanks for your PR. I'll look into it as soon as #27 is through. It might require some rebasing, but overall we should get some great improvements out of your cleanup.
> Thanks.

Your're welcome man! Do it in your time.

**Comment by mre** [comment]
@yurireeis could you rebase your PR on top of master? Alternatively, you could run the linters again on a clean master. A lot has changed now since we moved to a `DataProvider`. 😉

**Comment by mre** [comment]
Hey @yurireeis,
the code has quite diverged from `master` at this point.
In my mind it would be easiest if we closed this and added the improvements on a clean `master` branch. Feel free to reopen if you'd like to rebase the changes on top of `master`, though.
I'll close this for now to keep the repo clean but thanks for your contribution so far. I really appreciate it. ❤️

**Pull request closed without merging**
